services:
  hugo:
    image: klakegg/hugo:latest
    ports:
      - "1313:1313"
    volumes:
      - .:/src
    working_dir: /src
    command: server --bind 0.0.0.0
    environment:
      - HUGO_ENV=development